### ISSUE TITLE
Document missing options

### ISSUE THREAD

**Issue by phillipskevin** [donejs/done-serve#11]

**Comment by chasenlehara** [comment]
All of the options should be documented: https://github.com/donejs/done-serve/blob/8a1f4466009ff0ba92061ae242367fcc6f578e01/lib/cli/index.js#L9-L20

**Comment by chasenlehara** [comment]
Hey @matthewp, thanks for documenting `--static` in #16, but it looks like there are still some options that aren’t documented:
`--no-live-reload`
`--html5shiv`
`--live-reload-port`
`--steal-tools-path`
