### ISSUE TITLE
Not found: node_modules/done-serve/lib/index.js:14:7

### ISSUE THREAD

**Issue by MarcGodard** [donejs/done-serve#111]
On all my projects for donejs, I get the following error.

```
done-serve starting on http://localhost:8888
Live-reload server listening on port 8012
Error: File not found
    at notFoundHandler (/Users/marcgodard/GitHub/some-site/node_modules/done-serve/lib/index.js:14:7)
```

The file is there.

Node version v9.9.0
"done-serve": "^2.0.0"

**Comment by matthewp** [comment]
That line should only hit when using the `--static` flag, are you?

**Comment by MarcGodard** [comment]
@matthewp yes I am... but only because donejs defaults to it. I don't know what that does... lol

**Comment by matthewp** [comment]
DoneJS shouldn't default to that... are you running `donejs add app` or something else? It should produce this for the package.json scripts:

```json
{
  "test": "testee test.html --browsers firefox --reporter Spec",
  "start": "done-serve --port 8080",
  "develop": "done-serve --develop --port 8080",
  "build": "node build"
}
```

Without the --static. If you want to use SSR then remove the `--static` flag.  With that flag it acts as a static file server, so you'll get 404s unless you point it to specific files.

**Comment by MarcGodard** [comment]
@matthewp ok, maybe it was changed by someone for some reason. I will remove the static. Thanks.

**Comment by matthewp** [comment]
Cool, let me know if you have any more problems.
