### ISSUE TITLE
fs: re-evaluating native module sources is not supported

### ISSUE THREAD

**Issue by chasenlehara** [donejs/done-serve#14]
_I’m not sure if this is the right repo, so my apologies if this should be filed elsewhere._

With a fresh install of DoneJS and following [the guide](https://donejs.com/Guide.html), I’m seeing this message after running `donejs develop`:
![screen shot 2016-07-07 at 8 35 19 am](https://cloud.githubusercontent.com/assets/10070176/16659224/06d9c420-441e-11e6-97e4-5dd87a5c96a6.png)

As far as I can tell, it’s not causing any issues, although it’d be nice to have this fixed.

**Comment by matthewp** [comment]
I believe this will be fixed by https://github.com/donejs/done-serve/pull/12, but let's keep it open to be sure.

**Comment by justinbmeyer** [comment]
I didn't see this.
