### ISSUE TITLE
WebSocket connection to 'ws://localhost:8012/' failed

### ISSUE THREAD

**Issue by BigAB** [donejs/done-serve#19]
<img width="821" alt="screen shot 2016-11-22 at 10 54 32 pm" src="https://cloud.githubusercontent.com/assets/76821/20551516/b494ef68-b106-11e6-8dd4-41e7f8106b64.png">

> WebSocket connection to 'ws://localhost:8012/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED live-reload.js:245 

This is in every donejs app I have seen. I think there may be something wrong with the live-reload

**Comment by justinbmeyer** [comment]
@BigAB do you have the live reload server running?

**Comment by BigAB** [comment]
Just started a fresh donejs app install and this isn't happening.

Perhaps it was fixed since this issue was created? I'll keep an eye out for it again.
