### ISSUE TITLE
Warn when used in production

### ISSUE THREAD

**Issue by matthewp** [donejs/done-serve#37]
done-serve is not intended to be used as a production server. It doesn't include many important features you want in production like proper security headers. That stuff is really important and takes commitment that this project can't make. 

So I think the solution is to warn when used in production. To start we can look at `NODE_ENV`.

**Comment by frank-dspeed** [comment]
Maybe i should publish my Production nginx config? and some docker containers and stuff like that?

I run really large nodejs applications in production so i know whats needed 

i could prepare basic files like systemd unit files for startup and some install scripts for barbone or run via docker.

**Comment by matthewp** [comment]
yeah, having that kind of information out in the community would be awesome.

**Comment by frank-dspeed** [comment]
Ok i Start preparing a run donejs applications in Production Guide

**Comment by frank-dspeed** [comment]
https://github.com/direktspeed/donejs-production-guide

**Comment by matthewp** [comment]
Great! Thanks for doing that.

**Comment by matthewp** [comment]
Fixed in https://github.com/donejs/done-serve/pull/95
