### ISSUE TITLE
Add npm selfsigned

### ISSUE THREAD

**Issue by frank-dspeed** [donejs/done-serve#67]
https://www.npmjs.com/package/selfsigned

This will allow to create self-signed certs per project if not exist in .certs 

i think its a good idea to default to http2 to make that easyer we should auto create key pairs per application if not exist. and default to that 

make the settings for cert and pem file optional and enable http2 by default via private key pair.

**Comment by matthewp** [comment]
This is still under consideration. Since there isn't a great dev flow for SSL locally (the dev is always going to have to navigate through browser warnings) we are leaning towards not having h2 on by default.

**Comment by frank-dspeed** [comment]
@frank-dspeed i think supplying standardt insecure certs and pem for dev is totally ok and enable h2 by default. simply lets git commit standart files

**Comment by matthewp** [comment]
Let's take the conversation over to https://github.com/donejs/donejs/issues/1111 which is more or less the same as this one. That one has a picture of what the user faces when using a self-signed certificate on localhost. To get passed that you have to press Advanced and then "proceed to localhost". I think having that as a default workflow would be devastating for donejs' adoption.
