### ISSUE TITLE
What should be a 404 gets returned as a 500 error

### ISSUE THREAD

**Issue by matthewp** [donejs/done-serve#98]
Below is an example when we try to import a module that doesn't exist. This should be a 404 error, but instead returns as 500.

This prevents steal's fallback mechanism (used for searching for files within npm projects that obey npm's pathing algorithm).

<img width="1192" alt="screen shot 2018-02-26 at 11 44 44 am" src="https://user-images.githubusercontent.com/361671/36683039-901eb19c-1aea-11e8-9494-8e797f5d250e.png">

**Comment by cherifGsoul** [comment]
I'm not sure how I can reproduce the issue, now I see 404 in the terminal's console 
<img width="788" alt="screen shot 2019-01-10 at 9 39 13 pm" src="https://user-images.githubusercontent.com/109013/50995755-4eff4600-1520-11e9-8f37-919f5fe24c5f.png">

**Comment by matthewp** [comment]
I think this was a problem with the app I was working on. I can't think of a reason why this would instead produce 500. The normal 404 problem still exists with all donejs apps of course.
